//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionarAsignacionDeEspacios.h
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#if !defined(_GESTIONARASIGNACIONDEESPACIOS_H)
#define _GESTIONARASIGNACIONDEESPACIOS_H

#using <mscorlib.dll>

namespace Logica del Negocio {
	class GestionarAsignacionDeEspacios {
	public:
		boolean OcuparEspacios(String identificador);
		boolean liberarEspacio(String identificador);
		boolean VerificarEspacio(String identificador, Date calendar);
	};
}

#endif  //_GESTIONARASIGNACIONDEESPACIOS_H
