//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionarVigilante.cpp
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#include "GestionarVigilante.h"
#using <mscorlib.dll>

namespace Logica del Negocio {
	vigilante GestionarVigilante::agregarVigilante() {
	}
	
	vigilante GestionarVigilante::eliminarVigilante() {
	}
	
	vigilante GestionarVigilante::modificarVigilnte() {
	}
	
	vigilante GestionarVigilante::buscarVigilante() {
	}
	
}
