//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionUsuarios.cpp
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#include "GestionUsuarios.h"
#include "Usuario.h"
#using <mscorlib.dll>

namespace Logica del Negocio {
	void GestionUsuarios::agregarUsuario(Usuario Usuario) {
	}
	
	void GestionUsuarios::borrarUsuario(cedula int) {
	}
	
}
