//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Gestion Vehiculo.h
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#if !defined(_GESTION VEHICULO_H)
#define _GESTION VEHICULO_H

#using <mscorlib.dll>

namespace Logica del Negocio {
	class Gestion Vehiculo {
	public:
		vehiculo Vehiculo;
		void adicionarVehiculo();
		void consultarVehiculo();
	};
}

#endif  //_GESTION VEHICULO_H
