//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionarVigilante.h
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#if !defined(_GESTIONARVIGILANTE_H)
#define _GESTIONARVIGILANTE_H

#using <mscorlib.dll>

namespace Logica del Negocio {
	class GestionarVigilante {
	public:
		vigilante agregarVigilante();
		vigilante eliminarVigilante();
		vigilante modificarVigilnte();
		vigilante buscarVigilante();
	};
}

#endif  //_GESTIONARVIGILANTE_H
