//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionUsuarios.h
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#if !defined(_GESTIONUSUARIOS_H)
#define _GESTIONUSUARIOS_H

#include "Usuario.h"
#using <mscorlib.dll>

namespace Logica del Negocio {
	class GestionUsuarios {
	public:
		usuario Usuario;
		void agregarUsuario(Usuario Usuario);
		void borrarUsuario(cedula int);
	};
}

#endif  //_GESTIONUSUARIOS_H
