//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GestionarAsignacionDeEspacios.cpp
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#include "GestionarAsignacionDeEspacios.h"
#using <mscorlib.dll>

namespace Logica del Negocio {
	boolean GestionarAsignacionDeEspacios::OcuparEspacios(String identificador) {
	}
	
	boolean GestionarAsignacionDeEspacios::liberarEspacio(String identificador) {
	}
	
	boolean GestionarAsignacionDeEspacios::VerificarEspacio(String identificador, Date calendar) {
	}
	
}
