//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Gestion Vehiculo.cpp
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#include "Gestion Vehiculo.h"
#using <mscorlib.dll>

namespace Logica del Negocio {
	void Gestion Vehiculo::adicionarVehiculo() {
	}
	
	void Gestion Vehiculo::consultarVehiculo() {
	}
	
}
