//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Espacio.h
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#if !defined(_ESPACIO_H)
#define _ESPACIO_H

#using <mscorlib.dll>

namespace Entidades del Dominio {
	class Espacio {
	public:
		void OcuparEspacio(String tamaño, boolean TipoEspecial);
		boolean EspacioDisponible();
		boolean VerificarEspacio(String identificador);
		int getTamaño();
		String getIdentificador();
		String getUbicación();
		boolean getTipoEspacioLibre();
		String getDescripción();
	private:
		int tamañoM2;
		String identificador;
		String ubicación;
		boolean tipoEspecial;
		boolean espacioLibre;
		String descripción;
	};
}

#endif  //_ESPACIO_H
