//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Espacio.cpp
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#include "Espacio.h"
#using <mscorlib.dll>

namespace Entidades del Dominio {
	void Espacio::OcuparEspacio(String tamaño, boolean TipoEspecial) {
	}
	
	boolean Espacio::EspacioDisponible() {
	}
	
	boolean Espacio::VerificarEspacio(String identificador) {
	}
	
	int Espacio::getTamaño() {
	}
	
	String Espacio::getIdentificador() {
	}
	
	String Espacio::getUbicación() {
	}
	
	boolean Espacio::getTipoEspacioLibre() {
	}
	
	String Espacio::getDescripción() {
	}
	
}
