//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.h
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#if !defined(_USUARIO_H)
#define _USUARIO_H

#using <mscorlib.dll>

namespace Entidades del Dominio {
	class Usuario {
	public:
		int id;
		int cedula;
		string nombre;
		int celular;
		boolean genero;
		date fecha_cumple;
	};
}

#endif  //_USUARIO_H
