//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Vehiculo.h
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#if !defined(_VEHICULO_H)
#define _VEHICULO_H

#using <mscorlib.dll>

namespace Entidades del Dominio {
	class Vehiculo {
	public:
		int id;
		string placa;
		string propietario;
		string telefono;
		string marca;
		string color;
		string modelo;
		string motor;
		String getPlaca();
	};
}

#endif  //_VEHICULO_H
