//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Vehiculo.cpp
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#include "Vehiculo.h"
#using <mscorlib.dll>

namespace Entidades del Dominio {
	String Vehiculo::getPlaca() {
	}
	
}
