//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Vigilantes.h
//  @ Date : 05/08/2019
//  @ Author : 
//
//


#if !defined(_VIGILANTES_H)
#define _VIGILANTES_H

#using <mscorlib.dll>

namespace Entidades del Dominio {
	class Vigilantes {
	public:
		int cedula;
		String nombre;
		String apellidos;
		int telefono;
		String correo;
	};
}

#endif  //_VIGILANTES_H
